vsync = true;
backend = "glx";

corner-radius = 20;
detect-rounded-corners = true;
rounded-corners-exclude = [
    "window_type = 'fullscreen'",
];

blur:
{
    method = "box";
    size = 5;
    strength = 2;
};

blur-background = true;
blur-background-exclude = [
    "window_type = 'fullscreen'",
    "class_g = 'librewolf'",
    "class_g = 'steam'",
];

blur-rule = [
    "class_g = 'st'",
    "class_g = 'St'",
];

fading = true;
fade-delta = 3;
