[colors]
background = #101512
background-alt = #0d1510

foreground = #c2d6bc

primary = #9adf84
secondary = #6f9470
alert = #7da783
disabled = #4f7065

border-color = #1f3a2a
[bar/main]
width = 100%
height = 24pt

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 4pt

border-size = 2pt
border-color = ${colors.secondary}

padding-left = 0
padding-right = 1

module-margin = 2

separator = |
separator-foreground = ${colors.disabled}

font-0 = 0xProto Nerd Font;2

modules-left = xworkspaces xwindow
modules-right =  pulseaudio backlight battery xkeyboard memory cpu systray date

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

wm-restack = i3

; override-redirect = true

; This module is not active by default (to enable it, add it to one of the
; modules-* list above).
; Please note that only a single tray can exist at any time. If you launch
; multiple bars with this module, only a single one will show it, the others
; will produce a warning. Which bar gets the module is timing dependent and can
; be quite random.
; For more information, see the documentation page for this module:
; https://polybar.readthedocs.io/en/stable/user/modules/tray.html
[module/systray]
type = internal/tray

format-margin = 8pt
tray-spacing = 16pt

[module/xworkspaces]
type = internal/xworkspaces

label-active = %name%
label-active-background = ${colors.background-alt}
label-active-underline= ${colors.primary}
label-active-padding = 1

label-occupied = %name%
label-occupied-padding = 1

label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

background = ${colors.background-alt}
padding = 1

[module/xwindow]
type = internal/xwindow
label = %title:0:40:...%

background = ${colors.background-alt}
padding = 1

[module/pulseaudio]
type = internal/pulseaudio

format-volume = <ramp-volume> <label-volume>

label-volume = %percentage%%

label-muted = 
label-muted-foreground = ${colors.disabled}

ramp-volume-0 = 󰕿
ramp-volume-1 = 󰖀
ramp-volume-2 = 󰕾

ramp-volume-0-foreground = ${colors.primary}
ramp-volume-1-foreground = ${colors.primary}
ramp-volume-2-foreground = ${colors.primary}
 
click-right = ~/.config/i3/pavucontrol.sh

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock

label-layout = %layout%
label-layout-foreground = ${colors.primary}

label-indicator-padding = 2
label-indicator-margin = 1
label-indicator-foreground = ${colors.background}
label-indicator-background = ${colors.secondary}

[module/memory]
type = internal/memory
interval = 2
format-prefix = " "
format-prefix-foreground = ${colors.primary}
label =  %percentage_used%% (%used%)

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = " "
format-prefix-foreground = ${colors.primary}
label = %percentage:2%%

[network-base]
type = internal/network
interval = 5
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-disconnected = %{F#F0C674}%ifname%%{F#707880} disconnected

[module/date]
type = internal/date
interval = 1

date = %Y-%m-%d %H:%M:%S

label = %date%
label-foreground = ${colors.primary}

[module/backlight]
type = internal/backlight

card = intel_backlight

use-actual-brightness = true


format = <ramp> <label>

label = %percentage%%

ramp-0 = 󰃜
ramp-1 = 󰃜
ramp-2 = 󰃜
ramp-3 = 󰃛
ramp-4 = 󰃚

ramp-0-foreground = ${colors.primary}
ramp-1-foreground = ${colors.primary}
ramp-2-foreground = ${colors.primary}
ramp-3-foreground = ${colors.primary}
ramp-4-foreground = ${colors.primary}

[module/battery]
type = internal/battery

full-at = 99

low-at = 30

battery = BAT1
adapter = ACAD

time-format = %H:%M:%S

format-charging = <animation-charging> <label-charging>

format-discharging = <ramp-capacity> <label-discharging>

format-full = <ramp-capacity> <label-full>

format-low = <label-low>

label-charging = %percentage%% (+)

label-discharging = %percentage%%

label-full = %percentage%%

label-low = CHARGE YO THANG

ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 

ramp-capacity-0-foreground = ${colors.alert}
ramp-capacity-1-foreground = ${colors.secondary}
ramp-capacity-2-foreground = ${colors.secondary}
ramp-capacity-3-foreground = ${colors.primary}
ramp-capacity-4-foreground = ${colors.primary}

animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 

animation-charging-0-foreground = ${colors.primary}
animation-charging-1-foreground = ${colors.primary}
animation-charging-2-foreground = ${colors.primary}
animation-charging-3-foreground = ${colors.primary}
animation-charging-4-foreground = ${colors.primary}

animation-charging-framerate = 750

animation-low-0 = !
animation-low-1 = 
animation-low-framerate = 200

[settings]
screenchange-reload = true

; vim:ft=dosini
